# -*- coding: utf-8 -*-
"""01_22301142_22311003_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-MyYvl0bwQ5wxUQkHiev7kRt1s8JHlI

# IMPORT DATASET
"""

import pandas as pd

dataset = pd.read_csv("/content/hotel_bookings.csv")
dataset.head(10)

"""# **Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error, r2_score

print('Shape of the dataset is {}.'.format(dataset.shape))
print(f'This dataset contains {dataset.shape[0]} rows (data points) and {dataset.shape[1]} columns (features).')

"""# **Dataset Information**"""

dataset.info()

# Split numerical features
numerical_data = dataset.select_dtypes(include='number')
numerical_features = numerical_data.columns.tolist()
print(f'There are {len(numerical_features)} QUANTITATIVE (numerical) features:\n')
print(numerical_features)

print("\n" + "="*60)

# Split categorical features
categorical_data = dataset.select_dtypes(include='object')
categorical_features = categorical_data.columns.tolist()
print(f'\nThere are {len(categorical_features)} CATEGORICAL features:\n')
print(categorical_features)

print("\n" + "="*60)

print("Categorical Features and their unique values:\n")
for col in categorical_features:
    print(f"  {col}: {dataset[col].nunique()} unique values → {dataset[col].unique()[:5]} ...")

print("=== Summary Statistics — Numerical Features ===")
numerical_data.describe().T
print("=== Summary Statistics — Categorical Features ===")
categorical_data.describe().T
print("=== Variance of Numerical Features ===")
print(numerical_data.var())
print("=== Skewness of Numerical Features ===")
print(numerical_data.skew())

print("=== Missing Values per Feature ===")
missing = dataset.isnull().sum()
missing_percent = (dataset.isnull().sum() / len(dataset)) * 100
missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_percent})
print(missing_df[missing_df['Missing Count'] > 0])



"""# **Histograms of Numerical Features**"""

numerical_data.hist(figsize=(16, 14), bins=20)
plt.suptitle("Histograms of Numerical Features", fontsize=14)
plt.tight_layout()
plt.show()

print("=== Unique values in Numerical Features ===")
print(numerical_data.nunique())

print("\n=== Unique values in Categorical Features ===")
print(categorical_data.nunique())

for col in categorical_features:
    plt.figure(figsize=(10, 4))
    categorical_data[col].value_counts().sort_index().plot(kind='bar', rot=45)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Count')
    plt.tight_layout()
    plt.show()

"""# **Heatmap**"""

correlation_matrix = numerical_data.corr()

plt.figure(figsize=(14, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.3)
plt.title("Correlation Heatmap — All Numerical Features")
plt.tight_layout()
plt.show()

corr = numerical_data.corr('pearson')[['is_canceled']].sort_values(by='is_canceled', ascending=False)

plt.figure(figsize=(6, 10))
plt.title('Pearson Correlation with is_canceled')

sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.tight_layout()
plt.show()

class_counts = dataset.groupby("is_canceled").size()
total = dataset.shape[0]

outcome    = [0, 1]
count      = [class_counts[0], class_counts[1]]
percentage = [(class_counts[v] / total) * 100 for v in [0, 1]]

imbalance_df = pd.DataFrame({
    'is_canceled': outcome,
    'count': count,
    'percentage': percentage
})
print(imbalance_df)

sns.barplot(data=imbalance_df, x='is_canceled', y='percentage', palette='Set2')
plt.title("Class Distribution of is_canceled (Target Variable)")
plt.xlabel("is_canceled  (0 = Not Canceled,  1 = Canceled)")
plt.ylabel("Percentage (%)")
plt.tight_layout()
plt.show()

numerical_data.plot(
    kind='density', figsize=(16, 16),
    subplots=True, layout=(5, 4),
    title="Density Plots of Numerical Features",
    sharex=False
)
plt.tight_layout()
plt.show()

# Check missing values
print("=== Missing Values ===")
print(dataset.isnull().sum()[dataset.isnull().sum() > 0])

# SOLUTION: Drop 'company' (too many nulls), impute others

# 'company' has mostly missing values — drop the column
dataset.drop(columns=['company'], inplace=True)

# 'agent' has missing values — fill with 0 (no agent)
dataset['agent'].fillna(0, inplace=True)

# 'children' has very few missing — fill with 0
dataset['children'].fillna(0, inplace=True)

# 'country' has very few missing — fill with mode
dataset['country'].fillna(dataset['country'].mode()[0], inplace=True)

# Verify
print("Missing values after fix:")
print(dataset.isnull().sum()[dataset.isnull().sum() > 0])
print("No remaining nulls!" if dataset.isnull().sum().sum() == 0 else "Still has nulls")

from sklearn.preprocessing import LabelEncoder

# Check which columns need encoding
print("Categorical columns:", dataset.select_dtypes(include='object').columns.tolist())

# Drop 'reservation_status' — it directly leaks the target (data leakage!)
# Drop 'reservation_status_date' — date string, complex to use
dataset.drop(columns=['reservation_status', 'reservation_status_date'], inplace=True)

# Label encode all remaining categorical columns
le = LabelEncoder()
categorical_cols = dataset.select_dtypes(include='object').columns.tolist()

for col in categorical_cols:
    dataset[col] = le.fit_transform(dataset[col].astype(str))

print("Encoding done. Remaining object columns:", dataset.select_dtypes(include='object').columns.tolist())
dataset.head()

from sklearn.preprocessing import StandardScaler

# Separate features and target
X = dataset.drop(columns=['is_canceled'])
y = dataset['is_canceled']

# Scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print("Scaling done.")
X_scaled.describe().T

from sklearn.model_selection import train_test_split

# Stratified split to preserve class balance
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # stratified because dataset is imbalanced
)

print(f"Train size: {X_train.shape[0]} rows")
print(f"Test size:  {X_test.shape[0]} rows")
print(f"\nClass distribution in train:\n{y_train.value_counts(normalize=True)*100}")
print(f"\nClass distribution in test:\n{y_test.value_counts(normalize=True)*100}")

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
print("KNN Accuracy:", accuracy_score(y_test, knn_pred))

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=42)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

from sklearn.neural_network import MLPClassifier

nn = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=200, random_state=42)
nn.fit(X_train, y_train)
nn_pred = nn.predict(X_test)
print("Neural Network Accuracy:", accuracy_score(y_test, nn_pred))

#unsupervised kmeans

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
kmeans.fit(X_scaled)
cluster_labels = kmeans.labels_

# Visualize
plt.figure(figsize=(8, 5))
plt.scatter(X_scaled['lead_time'], X_scaled['adr'],
            c=cluster_labels, cmap='Set1', alpha=0.3, s=5)
plt.title("KMeans Clusters (lead_time vs adr)")
plt.xlabel("lead_time (scaled)")
plt.ylabel("adr (scaled)")
plt.colorbar(label='Cluster')
plt.tight_layout()
plt.show()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K_range = range(1, 10)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Plot
plt.figure(figsize=(6,4))
plt.plot(K_range, inertia, marker='o')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, roc_auc_score, roc_curve)

models_pred = {
    'KNN': knn_pred,
    'Logistic Regression': lr_pred,
    'Naive Bayes': nb_pred,
    'Neural Network': nn_pred
}

models_obj = {
    'KNN': knn,
    'Logistic Regression': lr,
    'Naive Bayes': nb,
    'Neural Network': nn
}

results = []
for name, pred in models_pred.items():
    proba = models_obj[name].predict_proba(X_test)[:, 1]
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, pred),
        'Precision': precision_score(y_test, pred),
        'Recall': recall_score(y_test, pred),
        'AUC': roc_auc_score(y_test, proba)
    })

results_df = pd.DataFrame(results).set_index('Model')
print(results_df.round(4))

#bar chart accuracy
results_df['Accuracy'].plot(kind='bar', figsize=(9, 5), color='steelblue', rot=30)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim(0.5, 1.0)
plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

for name, pred in models_pred.items():
    cm = confusion_matrix(y_test, pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

    plt.title(f"{name} Confusion Matrix")
    plt.xlabel('Predicted')
    plt.ylabel('Actual')

    plt.show()

#roc auc
plt.figure(figsize=(9, 6))
for name, obj in models_obj.items():
    proba = obj.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, proba)
    auc = roc_auc_score(y_test, proba)
    plt.plot(fpr, tpr, label=f'{name} (AUC = {auc:.3f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.title("ROC Curves — All Models")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.tight_layout()
plt.show()